import re

# --- 1. ROMAN NUMERAL NORMALIZATION ---
ROUND_MAP = {
    "I": 1, "II": 2, "III": 3, "IV": 4, "V": 5, 
    "VI": 6, "VII": 7, "VIII": 8, "IX": 9, "X": 10
}

# --- 2. SEMANTIC ARTIFACT CLASSIFICATION ---
P_TARGET_SELECTION = re.compile(r'(SELECTION LIST|ALLOTMENT LIST|SELECTED CANDIDATES)', re.IGNORECASE)

P_BLOCK_IGNORED = re.compile(
    r'(MERIT LIST|ELIGIBLE CANDIDATES|REGISTERED CANDIDATES|SEAT MATRIX|VACANCY|VIRTUAL VACANCY|NOTICE|SCHEDULE|FEE|BROCHURE|INSTRUCTION|APPLICATION FORM)', 
    re.IGNORECASE
)

# --- 3. ROUND TAXONOMY (STRICT IDENTIFIERS) ---
# [PATCHED] Longest-first Roman numeral matching up to X
P_ROUND_SEQ = re.compile(r'(?:ROUND|CAP|STRAY|PHASE)\s*[-_:]*\s*((?:X|IX|VIII|VII|VI|V|IV|III|II|I)|\d+)', re.IGNORECASE)

# Explicit types (Evaluated in strict conditional order)
P_ROUND_SPECIAL_STRAY = re.compile(r'(SPECIAL STRAY|EXTENDED STRAY)', re.IGNORECASE)
P_ROUND_STRAY = re.compile(r'\bSTRAY\b', re.IGNORECASE)
P_ROUND_INSTITUTIONAL = re.compile(r'(INSTITUTIONAL|INSTITUTE LEVEL|MANAGEMENT)', re.IGNORECASE)
P_ROUND_CAP = re.compile(r'\bCAP\b', re.IGNORECASE)

# --- 4. COURSE GROUPS (STRICT BOUNDARIES) ---
P_GROUP_MBBS_BDS = re.compile(r'\b(MBBS|BDS)\b', re.IGNORECASE)
P_GROUP_AYUSH = re.compile(r'\b(BAMS|BHMS|BUMS|AYUSH)\b', re.IGNORECASE)
P_GROUP_ALLIED = re.compile(r'\b(BPTH|BOTH|BASLP|BP&O|BNYS|ALLIED|NURSING)\b', re.IGNORECASE)

# --- 5. REVISIONS ---
P_REV_REVISED = re.compile(r'(REVISED|UPDATED|AMENDED)', re.IGNORECASE)
P_REV_CORRIGENDUM = re.compile(r'\bCORRIGENDUM\b', re.IGNORECASE)
P_REV_SUPPLEMENTARY = re.compile(r'\bSUPPLEMENTARY\b', re.IGNORECASE)

# --- 6. OCR DECONTAMINATION DICTIONARY ---
MH_KNOWN_CATEGORIES = [
    "SEBCHA", "EMSEBC", "EMOBC", "EMNTC", "EMNTD", "EMNTB", "EMVJA", "EMSC", "EMST", "EMNT",
    "OPEN", "SEBC", "NT1", "NT2", "NT3", "NTB", "NTC", "NTD", "OBC", "EWS", 
    "DEF1", "DEF2", "DEF3", "DEF", "VJA", "MKB", "HA", 
    "SC", "ST", "PWD", "AIQ", "NRI", "INST", "MNG", "MINORITY", "I\.?Q\.?"
]

P_SQUISHED_CAT_SPLITTER = re.compile(rf'^({"|".join(MH_KNOWN_CATEGORIES)})\s*(.*)$', re.IGNORECASE)
P_SQUISHED_ANCHOR = re.compile(rf'.*([MF])\s*((?:{"|".join(MH_KNOWN_CATEGORIES)}).*)', re.IGNORECASE)