"""add josaa metadata

Revision ID: 0dd998e36405
Revises: a47ff6bd90b7
Create Date: 2026-03-02 05:23:21.665453+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd998e36405'
down_revision: Union[str, None] = 'a47ff6bd90b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('josaa_college_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('institute_name_raw', sa.Text(), nullable=False),
    sa.Column('institute_type', sa.String(length=32), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'institute_name_raw', 'year', name='uq_josaa_metadata_identity')
    )
    op.create_index('idx_josaa_college_id', 'josaa_college_metadata', ['college_id'], unique=False)
    op.create_index('idx_josaa_name_lookup', 'josaa_college_metadata', ['institute_name_raw', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_josaa_name_lookup', table_name='josaa_college_metadata')
    op.drop_index('idx_josaa_college_id', table_name='josaa_college_metadata')
    op.drop_table('josaa_college_metadata')
    # ### end Alembic commands ###
