"""add_audit_columns_strict

Revision ID: 20046438ef26
Revises: c03a73faca1a
Create Date: 2026-01-24 19:00:26.388067+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20046438ef26'
down_revision: Union[str, None] = 'c03a73faca1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('college_candidates', 'ingestion_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('college_registry_normalized_name_key', 'college_registry', type_='unique')
    op.add_column('discovered_artifacts', sa.Column('exam_code', sa.String(length=32), nullable=False))
    op.add_column('discovered_artifacts', sa.Column('original_name', sa.Text(), nullable=True))
    op.add_column('discovered_artifacts', sa.Column('round_number', sa.Integer(), nullable=True))
    op.add_column('discovered_artifacts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('idx_discovered_pattern', table_name='discovered_artifacts')
    op.drop_index('idx_discovered_status', table_name='discovered_artifacts')
    op.create_index(op.f('ix_discovered_artifacts_exam_code'), 'discovered_artifacts', ['exam_code'], unique=False)
    op.create_index(op.f('ix_discovered_artifacts_pattern_classification'), 'discovered_artifacts', ['pattern_classification'], unique=False)
    op.create_index(op.f('ix_discovered_artifacts_status'), 'discovered_artifacts', ['status'], unique=False)
    op.create_index(op.f('ix_discovered_artifacts_updated_at'), 'discovered_artifacts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_seat_bucket_taxonomy_exam_code'), 'seat_bucket_taxonomy', ['exam_code'], unique=False)
    op.alter_column('seat_policy_quarantine', 'ingestion_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_policy_quarantine_bucket', table_name='seat_policy_quarantine')
    op.drop_index('idx_policy_quarantine_exam', table_name='seat_policy_quarantine')
    op.drop_index('idx_policy_quarantine_status', table_name='seat_policy_quarantine')
    op.create_index(op.f('ix_seat_policy_quarantine_exam_code'), 'seat_policy_quarantine', ['exam_code'], unique=False)
    op.create_index(op.f('ix_seat_policy_quarantine_seat_bucket_code'), 'seat_policy_quarantine', ['seat_bucket_code'], unique=False)
    op.create_index(op.f('ix_seat_policy_quarantine_status'), 'seat_policy_quarantine', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_policy_quarantine_status'), table_name='seat_policy_quarantine')
    op.drop_index(op.f('ix_seat_policy_quarantine_seat_bucket_code'), table_name='seat_policy_quarantine')
    op.drop_index(op.f('ix_seat_policy_quarantine_exam_code'), table_name='seat_policy_quarantine')
    op.create_index('idx_policy_quarantine_status', 'seat_policy_quarantine', ['status'], unique=False)
    op.create_index('idx_policy_quarantine_exam', 'seat_policy_quarantine', ['exam_code'], unique=False)
    op.create_index('idx_policy_quarantine_bucket', 'seat_policy_quarantine', ['seat_bucket_code'], unique=False)
    op.alter_column('seat_policy_quarantine', 'ingestion_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_seat_bucket_taxonomy_exam_code'), table_name='seat_bucket_taxonomy')
    op.drop_index(op.f('ix_discovered_artifacts_updated_at'), table_name='discovered_artifacts')
    op.drop_index(op.f('ix_discovered_artifacts_status'), table_name='discovered_artifacts')
    op.drop_index(op.f('ix_discovered_artifacts_pattern_classification'), table_name='discovered_artifacts')
    op.drop_index(op.f('ix_discovered_artifacts_exam_code'), table_name='discovered_artifacts')
    op.create_index('idx_discovered_status', 'discovered_artifacts', ['status'], unique=False)
    op.create_index('idx_discovered_pattern', 'discovered_artifacts', ['pattern_classification'], unique=False)
    op.drop_column('discovered_artifacts', 'updated_at')
    op.drop_column('discovered_artifacts', 'round_number')
    op.drop_column('discovered_artifacts', 'original_name')
    op.drop_column('discovered_artifacts', 'exam_code')
    op.create_unique_constraint('college_registry_normalized_name_key', 'college_registry', ['normalized_name'])
    op.alter_column('college_candidates', 'ingestion_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
