"""add college filter search entitlements and search credit ledger type

Revision ID: 37aaddd7057b
Revises: 6db4ece46e79
Create Date: 2026-04-28 15:40:53.642852+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37aaddd7057b'
down_revision: Union[str, None] = '6db4ece46e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE credit_ledger_entry_type_enum ADD VALUE IF NOT EXISTS 'SEARCH_CREDIT_CONSUMED'"
    )
    op.create_table('student_search_entitlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('search_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('request_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('entitlement_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumption_ledger_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumption_ledger_id'], ['student_credit_ledger.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_user_id'], ['student_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_user_id', 'search_fingerprint', name='uq_student_search_entitlement_student_fingerprint')
    )
    op.create_index('idx_student_search_entitlement_fingerprint', 'student_search_entitlements', ['search_fingerprint'], unique=False)
    op.create_index('idx_student_search_entitlement_student_expiry', 'student_search_entitlements', ['student_user_id', 'entitlement_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_student_search_entitlement_student_expiry', table_name='student_search_entitlements')
    op.drop_index('idx_student_search_entitlement_fingerprint', table_name='student_search_entitlements')
    op.drop_table('student_search_entitlements')
    # ### end Alembic commands ###
    # PostgreSQL enum values cannot be safely removed in-place in a simple downgrade.
    # We intentionally leave SEARCH_CREDIT_CONSUMED present in the enum type.
