"""phase_0_course_branch_registry

Revision ID: 396493a59849
Revises: b63a9533e925
Create Date: 2026-03-09 10:22:01.233504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396493a59849'
down_revision: Union[str, None] = 'b63a9533e925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_discovered_artifact_id_exam', 'discovered_artifacts', ['id', 'exam_code'])
    op.create_table('exam_branch_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("normalized_name = lower(regexp_replace(btrim(normalized_name), '[[:space:]]+', ' ', 'g'))", name='chk_branch_cand_norm_format'),
    sa.CheckConstraint("status IN ('PENDING', 'REJECTED')", name='chk_branch_cand_status'),
    sa.CheckConstraint('length(btrim(raw_name)) > 0', name='chk_branch_cand_raw_not_empty'),
    sa.ForeignKeyConstraint(['source_artifact_id', 'exam_code'], ['discovered_artifacts.id', 'discovered_artifacts.exam_code'], name='fk_branch_candidate_artifact', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_name', name='uq_branch_candidate_exam_norm')
    )
    op.create_index('idx_branch_candidate_status_time', 'exam_branch_candidates', ['exam_code', 'status', 'created_at'], unique=False)
    op.create_table('exam_branch_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('discipline', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=True),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.CheckConstraint("discipline = regexp_replace(btrim(discipline), '[[:space:]]+', ' ', 'g')", name='chk_branch_discipline_format'),
    sa.CheckConstraint("normalized_name = lower(regexp_replace(btrim(discipline), '[[:space:]]+', ' ', 'g')) || COALESCE(' - ' || lower(regexp_replace(btrim(variant), '[[:space:]]+', ' ', 'g')), '')", name='chk_branch_identity_determinism'),
    sa.CheckConstraint("variant IS NULL OR variant = regexp_replace(btrim(variant), '[[:space:]]+', ' ', 'g')", name='chk_branch_variant_format'),
    sa.ForeignKeyConstraint(['exam_code'], ['exam_configuration.exam_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_name', name='uq_branch_registry_exam_norm'),
    sa.UniqueConstraint('id', 'exam_code', name='uq_branch_registry_id_exam')
    )
    op.create_index('idx_branch_registry_discipline', 'exam_branch_registry', ['exam_code', 'discipline'], unique=False)
    op.create_index('idx_branch_var_notnull', 'exam_branch_registry', ['exam_code', sa.text('lower(discipline)'), sa.text('lower(variant)')], unique=True, postgresql_where=sa.text('variant IS NOT NULL'))
    op.create_index('idx_branch_var_null', 'exam_branch_registry', ['exam_code', sa.text('lower(discipline)')], unique=True, postgresql_where=sa.text('variant IS NULL'))
    op.create_table('exam_course_type_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("normalized_name = lower(regexp_replace(btrim(normalized_name), '[[:space:]]+', ' ', 'g'))", name='chk_course_cand_norm_format'),
    sa.CheckConstraint("status IN ('PENDING', 'REJECTED')", name='chk_course_cand_status'),
    sa.CheckConstraint('length(btrim(raw_name)) > 0', name='chk_course_cand_raw_not_empty'),
    sa.ForeignKeyConstraint(['source_artifact_id', 'exam_code'], ['discovered_artifacts.id', 'discovered_artifacts.exam_code'], name='fk_course_candidate_artifact', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_name', name='uq_course_candidate_exam_norm')
    )
    op.create_index('idx_course_candidate_status_time', 'exam_course_type_candidates', ['exam_code', 'status', 'created_at'], unique=False)
    op.create_table('exam_course_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.CheckConstraint("canonical_name = regexp_replace(btrim(canonical_name), '[[:space:]]+', ' ', 'g')", name='chk_course_type_canonical_format'),
    sa.CheckConstraint("normalized_name = lower(regexp_replace(btrim(canonical_name), '[[:space:]]+', ' ', 'g'))", name='chk_course_type_identity_determinism'),
    sa.ForeignKeyConstraint(['exam_code'], ['exam_configuration.exam_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_name', name='uq_course_type_exam_norm'),
    sa.UniqueConstraint('id', 'exam_code', name='uq_course_type_id_exam')
    )
    op.create_table('exam_branch_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.CheckConstraint("normalized_alias = lower(regexp_replace(btrim(normalized_alias), '[[:space:]]+', ' ', 'g'))", name='chk_branch_alias_format'),
    sa.ForeignKeyConstraint(['branch_id', 'exam_code'], ['exam_branch_registry.id', 'exam_branch_registry.exam_code'], name='fk_branch_alias_to_registry', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_alias', name='uq_branch_alias_exam_norm')
    )
    op.create_index('idx_branch_alias_parent', 'exam_branch_aliases', ['branch_id'], unique=False)
    op.create_table('exam_course_type_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('course_type_id', sa.UUID(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.CheckConstraint("normalized_alias = lower(regexp_replace(btrim(normalized_alias), '[[:space:]]+', ' ', 'g'))", name='chk_course_alias_format'),
    sa.ForeignKeyConstraint(['course_type_id', 'exam_code'], ['exam_course_types.id', 'exam_course_types.exam_code'], name='fk_course_alias_to_registry', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_code', 'normalized_alias', name='uq_course_alias_exam_norm')
    )
    op.create_index('idx_course_type_alias_parent', 'exam_course_type_aliases', ['course_type_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_course_type_alias_parent', table_name='exam_course_type_aliases')
    op.drop_table('exam_course_type_aliases')
    op.drop_index('idx_branch_alias_parent', table_name='exam_branch_aliases')
    op.drop_table('exam_branch_aliases')
    op.drop_table('exam_course_types')
    op.drop_index('idx_course_candidate_status_time', table_name='exam_course_type_candidates')
    op.drop_table('exam_course_type_candidates')
    op.drop_index('idx_branch_var_null', table_name='exam_branch_registry', postgresql_where=sa.text('variant IS NULL'))
    op.drop_index('idx_branch_var_notnull', table_name='exam_branch_registry', postgresql_where=sa.text('variant IS NOT NULL'))
    op.drop_index('idx_branch_registry_discipline', table_name='exam_branch_registry')
    op.drop_table('exam_branch_registry')
    op.drop_index('idx_branch_candidate_status_time', table_name='exam_branch_candidates')
    op.drop_table('exam_branch_candidates')
    op.drop_constraint('uq_discovered_artifact_id_exam', 'discovered_artifacts', type_='unique')
    # ### end Alembic commands ###
