"""Add requires_reprocessing column

Revision ID: 3f1d8b2818b8
Revises: 20046438ef26
Create Date: 2026-01-30 15:38:38.213482+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1d8b2818b8'
down_revision: Union[str, None] = '20046438ef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_artifacts', sa.Column('requires_reprocessing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_artifacts', 'requires_reprocessing')
    # ### end Alembic commands ###
