"""enforce_media_lifecycle_and_hash_uniqueness

Revision ID: 436eae343c92
Revises: 49f6f0421bb6
Create Date: 2026-03-03 19:29:11.373105+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436eae343c92'
down_revision: Union[str, None] = '49f6f0421bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_college_content_hash', 'college_media', ['college_id', 'content_hash'])
    op.create_index('uq_pending_college_media', 'college_media', ['college_id', 'media_type'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pending_college_media', table_name='college_media')
    op.drop_constraint('uq_college_content_hash', 'college_media', type_='unique')
    # ### end Alembic commands ###
