"""add_college_media_table

Revision ID: 49f6f0421bb6
Revises: 0dd998e36405
Create Date: 2026-03-03 05:59:10.553383+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f6f0421bb6'
down_revision: Union[str, None] = '0dd998e36405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('LOGO', 'CAMPUS_HERO', name='media_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='media_status_enum'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_college_media_hash_lookup', 'college_media', ['college_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_college_media_college_id'), 'college_media', ['college_id'], unique=False)
    op.create_index(op.f('ix_college_media_content_hash'), 'college_media', ['content_hash'], unique=False)
    op.create_index(op.f('ix_college_media_storage_key'), 'college_media', ['storage_key'], unique=False)
    op.create_index('uq_active_college_media', 'college_media', ['college_id', 'media_type'], unique=True, postgresql_where=sa.text("status = 'ACCEPTED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_college_media', table_name='college_media', postgresql_where=sa.text("status = 'ACCEPTED'"))
    op.drop_index(op.f('ix_college_media_storage_key'), table_name='college_media')
    op.drop_index(op.f('ix_college_media_content_hash'), table_name='college_media')
    op.drop_index(op.f('ix_college_media_college_id'), table_name='college_media')
    op.drop_index('idx_college_media_hash_lookup', table_name='college_media')
    op.drop_table('college_media')
    # ### end Alembic commands ###
