"""add location enrichment tables

Revision ID: 4f363064b6f5
Revises: 396493a59849
Create Date: 2026-03-10 15:10:35.446199+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f363064b6f5'
down_revision: Union[str, None] = '396493a59849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_location_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=16), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('raw_provider_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='location_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_location_candidates_college_id'), 'college_location_candidates', ['college_id'], unique=False)
    op.create_index('uq_pending_location_candidate', 'college_location_candidates', ['college_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('college_locations',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=16), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id')
    )
    op.create_index('idx_location_district', 'college_locations', ['district'], unique=False)
    op.create_index('idx_location_pincode', 'college_locations', ['pincode'], unique=False)
    op.create_index('idx_location_state_city', 'college_locations', ['state_code', 'city'], unique=False)
    op.create_table('location_dispatch_locks',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id')
    )
    op.create_table('location_ingestion_tracker',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_exhausted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_ingestion_tracker')
    op.drop_table('location_dispatch_locks')
    op.drop_index('idx_location_state_city', table_name='college_locations')
    op.drop_index('idx_location_pincode', table_name='college_locations')
    op.drop_index('idx_location_district', table_name='college_locations')
    op.drop_table('college_locations')
    op.drop_index('uq_pending_location_candidate', table_name='college_location_candidates', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_college_location_candidates_college_id'), table_name='college_location_candidates')
    op.drop_table('college_location_candidates')
    # ### end Alembic commands ###
