"""Add source_artifact_id to kcet metadata

Revision ID: 55a25fe2c51f
Revises: 3f1d8b2818b8
Create Date: 2026-01-31 14:59:21.764061+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a25fe2c51f'
down_revision: Union[str, None] = '3f1d8b2818b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kcet_college_metadata', sa.Column('source_artifact_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kcet_college_metadata', 'source_artifact_id')
    # ### end Alembic commands ###
