"""add college filter serving metadata and read model tables

Revision ID: 58691c771edc
Revises: 317b71d0e65e
Create Date: 2026-03-21 07:41:29.953951+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58691c771edc'
down_revision: Union[str, None] = '317b71d0e65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_path_catalog',
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('parent_path_id', sa.UUID(), nullable=True),
    sa.Column('path_key', sa.String(length=64), nullable=False),
    sa.Column('visible_label', sa.String(length=128), nullable=False),
    sa.Column('exam_family', sa.String(length=64), nullable=False),
    sa.Column('resolved_exam_code', sa.String(length=32), nullable=True),
    sa.Column('education_type', sa.String(length=64), nullable=True),
    sa.Column('selection_type', sa.String(length=64), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('expected_max_rounds', sa.Integer(), nullable=False),
    sa.Column('supports_branch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_course_relaxation', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supports_location_filter', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supports_opening_rank', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("metric_type IN ('rank', 'percentile')", name='ck_exam_path_metric_type'),
    sa.CheckConstraint('expected_max_rounds > 0', name='ck_exam_path_expected_max_rounds_positive'),
    sa.ForeignKeyConstraint(['parent_path_id'], ['exam_path_catalog.path_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('path_id'),
    sa.UniqueConstraint('path_key', name='uq_exam_path_catalog_path_key')
    )
    op.create_index('idx_exam_path_active_order', 'exam_path_catalog', ['active', 'display_order'], unique=False)
    op.create_index('idx_exam_path_family', 'exam_path_catalog', ['exam_family'], unique=False)
    op.create_table('exam_path_filter_schema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('filter_key', sa.String(length=64), nullable=False),
    sa.Column('filter_label', sa.String(length=128), nullable=False),
    sa.Column('control_type', sa.Enum('SELECT', 'AUTOCOMPLETE', 'NUMBER_INPUT', 'HIDDEN', name='filter_control_type_enum'), nullable=False),
    sa.Column('option_source', sa.Enum('STATIC', 'SERVING_MAP', 'LOCATION', 'BRANCH', 'PATH_OPTION', name='filter_option_source_enum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_auto_fillable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('depends_on_filter_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'filter_key', name='uq_exam_path_filter_schema_path_filter')
    )
    op.create_index('idx_exam_path_filter_schema_order', 'exam_path_filter_schema', ['path_id', 'sort_order'], unique=False)
    op.create_table('exam_path_option_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('course_type_value', sa.String(length=64), nullable=True),
    sa.Column('option_label', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_path_option_map_active', 'exam_path_option_map', ['path_id', 'active'], unique=False)
    op.create_index('idx_exam_path_option_map_path_exam', 'exam_path_option_map', ['path_id', 'exam_code'], unique=False)
    op.create_table('exam_program_serving_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('branch_option_key', sa.String(length=128), nullable=False),
    sa.Column('branch_label', sa.String(length=255), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=True),
    sa.Column('mapping_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('mapping_status', sa.Enum('AUTO_APPROVED', 'APPROVED', 'PENDING_REVIEW', 'REJECTED', name='mapping_status_enum'), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'branch_option_key', 'program_code', name='uq_exam_program_serving_map_path_branch_program')
    )
    op.create_index('idx_exam_program_serving_map_branch', 'exam_program_serving_map', ['path_id', 'branch_option_key'], unique=False)
    op.create_index('idx_exam_program_serving_map_program', 'exam_program_serving_map', ['path_id', 'program_code'], unique=False)
    op.create_index('idx_exam_program_serving_map_status', 'exam_program_serving_map', ['path_id', 'mapping_status'], unique=False)
    op.create_table('exam_seat_filter_serving_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('filter_key', sa.String(length=64), nullable=False),
    sa.Column('option_key', sa.String(length=128), nullable=False),
    sa.Column('option_label', sa.String(length=255), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=True),
    sa.Column('course_type', sa.String(length=64), nullable=True),
    sa.Column('location_type', sa.String(length=32), nullable=True),
    sa.Column('reservation_type', sa.String(length=64), nullable=True),
    sa.Column('seat_bucket_code', sa.String(length=128), nullable=True),
    sa.Column('display_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'filter_key', 'option_key', 'seat_bucket_code', name='uq_exam_seat_filter_serving_map_scope')
    )
    op.create_index('idx_exam_seat_filter_serving_map_bucket', 'exam_seat_filter_serving_map', ['path_id', 'seat_bucket_code'], unique=False)
    op.create_index('idx_exam_seat_filter_serving_map_lookup', 'exam_seat_filter_serving_map', ['path_id', 'filter_key', 'option_key'], unique=False)
    op.create_table('probability_policy_config',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('weight_round_evidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weight_round_stability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weight_current_year_presence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weight_margin', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weight_confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('probability_base', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('probability_multiplier', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('probability_min', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('probability_max', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('safe_min_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('safe_min_confidence', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('moderate_min_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('moderate_min_confidence', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('hard_min_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('hard_min_confidence', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('suggested_min_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('suggested_min_confidence', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('suggested_score_penalty', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('suggested_probability_penalty', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cold_start_probability_cap', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cold_start_safe_min_margin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cold_start_safe_min_confidence', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_no > 0', name='ck_probability_policy_version_positive'),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('policy_key', name='uq_probability_policy_config_key')
    )
    op.create_index('idx_probability_policy_active', 'probability_policy_config', ['is_active'], unique=False)
    op.create_index('idx_probability_policy_path', 'probability_policy_config', ['path_id', 'is_active'], unique=False)
    op.create_table('round_projection_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('seat_bucket_code', sa.String(length=128), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('same_round_mean', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('same_round_median', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('same_round_stddev', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('same_round_observation_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('relaxation_ratio_from_prev_round', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('current_year_presence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('round_evidence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('round_stability_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_years', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'seat_bucket_code', 'program_code', 'round_number', name='uq_round_projection_stats_scope')
    )
    op.create_index('idx_round_projection_stats_exam_round', 'round_projection_stats', ['exam_code', 'round_number'], unique=False)
    op.create_index('idx_round_projection_stats_lookup', 'round_projection_stats', ['path_id', 'seat_bucket_code', 'program_code'], unique=False)
    op.create_table('search_read_model_builds',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='search_build_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_reason', sa.String(length=64), nullable=False),
    sa.Column('trigger_exam_code', sa.String(length=32), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('source_latest_ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('source_watermark_year', sa.Integer(), nullable=True),
    sa.Column('source_watermark_round', sa.Integer(), nullable=True),
    sa.Column('rows_written', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['probability_policy_config.policy_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_index('idx_search_read_model_builds_status_started', 'search_read_model_builds', ['status', 'started_at'], unique=False)
    op.create_table('search_read_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('path_key', sa.String(length=64), nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('live_round_number', sa.Integer(), nullable=False),
    sa.Column('comparison_year', sa.Integer(), nullable=False),
    sa.Column('comparison_round_number', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('college_name', sa.Text(), nullable=False),
    sa.Column('institute_code', sa.String(length=64), nullable=False),
    sa.Column('institute_name', sa.Text(), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=False),
    sa.Column('branch_option_key', sa.String(length=128), nullable=True),
    sa.Column('seat_bucket_code', sa.String(length=128), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.Column('reservation_type', sa.String(length=64), nullable=True),
    sa.Column('location_type', sa.String(length=32), nullable=True),
    sa.Column('course_type', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=16), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('hero_storage_key', sa.String(), nullable=True),
    sa.Column('hero_public_url', sa.Text(), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('opening_rank', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('closing_rank', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cutoff_percentile', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('current_round_cutoff_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_projected_current_round', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('round_evidence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('round_stability_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('current_year_presence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_authority', sa.Text(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_year_available', sa.Integer(), nullable=False),
    sa.Column('latest_round_available', sa.Integer(), nullable=False),
    sa.Column('active_policy_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_policy_id'], ['probability_policy_config.policy_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['build_id'], ['search_read_model_builds.build_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['exam_path_catalog.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_read_model_branch', 'search_read_model', ['path_id', 'branch_option_key'], unique=False)
    op.create_index('idx_search_read_model_bucket', 'search_read_model', ['path_id', 'seat_bucket_code'], unique=False)
    op.create_index('idx_search_read_model_cursor', 'search_read_model', ['path_id', 'comparison_year', 'comparison_round_number', 'current_round_cutoff_value', 'college_id'], unique=False)
    op.create_index('idx_search_read_model_location', 'search_read_model', ['path_id', 'state_code', 'district'], unique=False)
    op.create_index('idx_search_read_model_metric_round', 'search_read_model', ['path_id', 'live_round_number', 'metric_type'], unique=False)
    op.create_index('idx_search_read_model_primary_filter', 'search_read_model', ['path_id', 'category_name', 'comparison_year', 'comparison_round_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_search_read_model_primary_filter', table_name='search_read_model')
    op.drop_index('idx_search_read_model_metric_round', table_name='search_read_model')
    op.drop_index('idx_search_read_model_location', table_name='search_read_model')
    op.drop_index('idx_search_read_model_cursor', table_name='search_read_model')
    op.drop_index('idx_search_read_model_bucket', table_name='search_read_model')
    op.drop_index('idx_search_read_model_branch', table_name='search_read_model')
    op.drop_table('search_read_model')
    op.drop_index('idx_search_read_model_builds_status_started', table_name='search_read_model_builds')
    op.drop_table('search_read_model_builds')
    op.drop_index('idx_round_projection_stats_lookup', table_name='round_projection_stats')
    op.drop_index('idx_round_projection_stats_exam_round', table_name='round_projection_stats')
    op.drop_table('round_projection_stats')
    op.drop_index('idx_probability_policy_path', table_name='probability_policy_config')
    op.drop_index('idx_probability_policy_active', table_name='probability_policy_config')
    op.drop_table('probability_policy_config')
    op.drop_index('idx_exam_seat_filter_serving_map_lookup', table_name='exam_seat_filter_serving_map')
    op.drop_index('idx_exam_seat_filter_serving_map_bucket', table_name='exam_seat_filter_serving_map')
    op.drop_table('exam_seat_filter_serving_map')
    op.drop_index('idx_exam_program_serving_map_status', table_name='exam_program_serving_map')
    op.drop_index('idx_exam_program_serving_map_program', table_name='exam_program_serving_map')
    op.drop_index('idx_exam_program_serving_map_branch', table_name='exam_program_serving_map')
    op.drop_table('exam_program_serving_map')
    op.drop_index('idx_exam_path_option_map_path_exam', table_name='exam_path_option_map')
    op.drop_index('idx_exam_path_option_map_active', table_name='exam_path_option_map')
    op.drop_table('exam_path_option_map')
    op.drop_index('idx_exam_path_filter_schema_order', table_name='exam_path_filter_schema')
    op.drop_table('exam_path_filter_schema')
    op.drop_index('idx_exam_path_family', table_name='exam_path_catalog')
    op.drop_index('idx_exam_path_active_order', table_name='exam_path_catalog')
    op.drop_table('exam_path_catalog')
    op.execute("DROP TYPE IF EXISTS search_build_status_enum")
    op.execute("DROP TYPE IF EXISTS mapping_status_enum")
    op.execute("DROP TYPE IF EXISTS filter_option_source_enum")
    op.execute("DROP TYPE IF EXISTS filter_control_type_enum")
    # ### end Alembic commands ###
