"""Longer Limit for exam program serving map keys

Revision ID: 8b5f44d06f93
Revises: 02f7dd9d4199
Create Date: 2026-04-01 09:57:03.776176+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5f44d06f93'
down_revision: Union[str, None] = '02f7dd9d4199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_program_serving_map', 'branch_option_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('exam_program_serving_map', 'branch_discipline_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('exam_program_serving_map', 'specialization_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_program_serving_map', 'specialization_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('exam_program_serving_map', 'branch_discipline_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('exam_program_serving_map', 'branch_option_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
