"""add_hardened_admin_tables

Revision ID: 99a15aa0b2bd
Revises: 34fb93569ff2
Create Date: 2026-02-09 05:50:44.335630+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a15aa0b2bd'
down_revision: Union[str, None] = '34fb93569ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create Admin Users Table
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'EDITOR', 'VIEWER', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    
    # 2. Create Admin Audit Trail Table
    op.create_table('admin_audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_resource', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_audit_admin_created', 'admin_audit_trail', ['admin_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_trail_action'), 'admin_audit_trail', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_trail_created_at'), 'admin_audit_trail', ['created_at'], unique=False)
    
    # [REMOVED] Drop commands for existing indexes to preserve performance
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse index creation
    op.drop_index(op.f('ix_admin_audit_trail_created_at'), table_name='admin_audit_trail')
    op.drop_index(op.f('ix_admin_audit_trail_action'), table_name='admin_audit_trail')
    op.drop_index('idx_admin_audit_admin_created', table_name='admin_audit_trail')
    
    # Reverse table creation
    op.drop_table('admin_audit_trail')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    
    # [REMOVED] Re-creation commands for the indexes we didn't drop
    # ### end Alembic commands ###