"""Add MHTCET college metadata table

Revision ID: a47ff6bd90b7
Revises: f1de33360dc6
Create Date: 2026-02-23 11:28:12.038479+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47ff6bd90b7'
down_revision: Union[str, None] = 'f1de33360dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mhtcet_college_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('dte_code', sa.String(length=50), nullable=False),
    sa.Column('dte_name_raw', sa.Text(), nullable=False),
    sa.Column('course_type', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dte_code', 'course_type', 'year', name='uq_mhtcet_metadata_identity')
    )
    op.create_index('idx_mhtcet_code_lookup', 'mhtcet_college_metadata', ['dte_code', 'year'], unique=False)
    op.create_index('idx_mhtcet_college_id', 'mhtcet_college_metadata', ['college_id'], unique=False)
    op.create_index(op.f('ix_mhtcet_college_metadata_dte_code'), 'mhtcet_college_metadata', ['dte_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mhtcet_college_metadata_dte_code'), table_name='mhtcet_college_metadata')
    op.drop_index('idx_mhtcet_college_id', table_name='mhtcet_college_metadata')
    op.drop_index('idx_mhtcet_code_lookup', table_name='mhtcet_college_metadata')
    op.drop_table('mhtcet_college_metadata')
    # ### end Alembic commands ###
