"""init_cutoff_outcomes_sot

Revision ID: abc1e382caff
Revises: 
Create Date: 2026-01-06 06:32:36.300659+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc1e382caff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutoff_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_code', sa.String(length=32), nullable=False),
    sa.Column('state_code', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('institute_code', sa.String(length=64), nullable=False),
    sa.Column('institute_name', sa.Text(), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=False),
    sa.Column('seat_bucket_code', sa.String(length=128), nullable=False),
    sa.Column('opening_rank', sa.Integer(), nullable=True),
    sa.Column('closing_rank', sa.Integer(), nullable=False),
    sa.Column('cutoff_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cutoff_percentile', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_authority', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    # NOTE: Removed standard UniqueConstraint to allow multiple history rows
    )

    # 1. Fast Filter Index (unchanged)
    op.create_index('idx_cutoff_fast_query', 'cutoff_outcomes', ['exam_code', 'state_code', 'year', 'round_number', 'is_latest'], unique=False)
    
    # 2. Institute Lookup (unchanged)
    op.create_index('idx_cutoff_institute', 'cutoff_outcomes', ['institute_code', 'program_code', 'is_latest'], unique=False)
    
    # 3. Rank Search (OPTIMIZED: Added is_latest to filter out history scans)
    op.create_index('idx_cutoff_rank_latest', 'cutoff_outcomes', ['closing_rank', 'is_latest'], unique=False)
    
    # 4. Seat Bucket Lookup (unchanged)
    op.create_index('idx_cutoff_seat_bucket', 'cutoff_outcomes', ['seat_bucket_code'], unique=False)

    # 5. ENTERPRISE FIX: Partial Unique Index
    # This ensures only ONE "is_latest=True" row exists per bucket,
    # while allowing unlimited "is_latest=False" (history) rows.
    op.create_index(
        'uq_cutoff_latest_only',
        'cutoff_outcomes',
        [
            'exam_code', 'state_code', 'year', 'round_number',
            'institute_code', 'program_code', 'seat_bucket_code'
        ],
        unique=True,
        postgresql_where=sa.text('is_latest = true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cutoff_latest_only', table_name='cutoff_outcomes', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_cutoff_seat_bucket', table_name='cutoff_outcomes')
    op.drop_index('idx_cutoff_rank_latest', table_name='cutoff_outcomes')
    op.drop_index('idx_cutoff_institute', table_name='cutoff_outcomes')
    op.drop_index('idx_cutoff_fast_query', table_name='cutoff_outcomes')
    op.drop_table('cutoff_outcomes')
    # ### end Alembic commands ###