"""add_media_governance_plane

Revision ID: b63a9533e925
Revises: 436eae343c92
Create Date: 2026-03-04 17:01:07.670659+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63a9533e925'
down_revision: Union[str, None] = '436eae343c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_dispatch_locks',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id', 'media_type')
    )
    op.create_table('media_ingestion_tracker',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_exhausted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('college_id', 'media_type')
    )
    op.create_index('idx_media_lateral_fetch', 'college_media', ['college_id', 'media_type', sa.text('ingested_at DESC')], unique=False)
    op.create_index('idx_college_pagination', 'college_registry', ['canonical_name', 'college_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_college_pagination', table_name='college_registry')
    op.drop_index('idx_media_lateral_fetch', table_name='college_media')
    op.drop_table('media_ingestion_tracker')
    op.drop_table('media_dispatch_locks')
    # ### end Alembic commands ###
