"""add_neet_college_metadata_table

Revision ID: f1de33360dc6
Revises: a9ef6b52310c
Create Date: 2026-02-20 16:03:54.814088+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1de33360dc6'
down_revision: Union[str, None] = 'a9ef6b52310c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neet_college_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('kea_college_code', sa.String(length=16), nullable=False),
    sa.Column('kea_college_name_raw', sa.Text(), nullable=False),
    sa.Column('course_type', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college_registry.college_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'course_type', 'year', name='uq_neet_metadata_identity'),
    sa.UniqueConstraint('kea_college_code', 'course_type', 'year', name='uq_neet_metadata_code_year')
    )
    op.create_index('idx_neet_code_lookup', 'neet_college_metadata', ['kea_college_code', 'year'], unique=False)
    op.create_index('idx_neet_college_id', 'neet_college_metadata', ['college_id'], unique=False)
    op.drop_constraint('uq_discovered_pdf', 'discovered_artifacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_discovered_pdf', 'discovered_artifacts', ['pdf_path', 'notification_url'])
    op.drop_index('idx_neet_college_id', table_name='neet_college_metadata')
    op.drop_index('idx_neet_code_lookup', table_name='neet_college_metadata')
    op.drop_table('neet_college_metadata')
    # ### end Alembic commands ###
